<?php
/**
 * Filtry sklepu — generowane automatycznie przez import.php
 * Ostatnia aktualizacja: 2026-02-11 15:21:04
 * NIE EDYTUJ RĘCZNIE — zmiany zostaną nadpisane przy następnym imporcie
 */

$filters = [
    1 => [
        'key'   => 'brand',
        'label' => 'Marka',
        'values' => [
            1 => 'Borbet',
            2 => 'Brock',
            3 => 'CForged',
            4 => 'Carbonado',
            5 => 'Carmani',
            6 => 'Concaver',
            7 => 'Diewe Wheels',
            8 => 'JR Wheels',
            9 => 'Keskin Tuning',
            10 => 'Klutch Wheels',
            11 => 'MAM Leichtmetallräder',
            12 => 'Magline',
            13 => 'Oxigin',
            14 => 'RC-DESIGN',
            15 => 'Ronal',
            16 => 'Wrath Wheels',
            17 => 'seventy9',
        ],
    ],
    2 => [
        'key'   => 'size',
        'label' => 'Rozmiar',
        'values' => [
            1 => '13"',
            2 => '14"',
            3 => '15"',
            4 => '16"',
            5 => '17"',
            6 => '18"',
            7 => '19"',
            8 => '20"',
            9 => '21"',
            10 => '22"',
            11 => '23"',
            12 => '24"',
        ],
    ],
    3 => [
        'key'   => 'width',
        'label' => 'Szerokość',
        'values' => [
            1 => '5.0J',
            2 => '5.5J',
            3 => '6.0J',
            4 => '6.5J',
            5 => '7.0J',
            6 => '7.5J',
            7 => '8.0J',
            8 => '8.5J',
            9 => '9.0J',
            10 => '9.5J',
            11 => '10.0J',
            12 => '10.5J',
            13 => '11.0J',
            14 => '11.5J',
            15 => '12.0J',
        ],
    ],
    4 => [
        'key'   => 'et',
        'label' => 'Offset ET',
        'values' => [
            1 => 'Poniżej 0',
            2 => 'ET 0-10',
            3 => 'ET 10-20',
            4 => 'ET 20-30',
            5 => 'ET 30-40',
            6 => 'ET 40-50',
            7 => 'ET 50-60',
            8 => 'ET 60-70',
            9 => 'ET 70-80',
            10 => 'ET 80-90',
        ],
    ],
    5 => [
        'key'   => 'color',
        'label' => 'Kolor',
        'values' => [
            1 => 'Biały',
            2 => 'Brązowy',
            3 => 'Chrom',
            4 => 'Czarny',
            5 => 'Czerwony',
            6 => 'Fioletowy',
            7 => 'Grafitowy',
            8 => 'Inne',
            9 => 'Kolorowe',
            10 => 'Srebrny',
            11 => 'Szary',
            12 => 'Tytanowy',
            13 => 'Złoty',
        ],
    ],
];
