<?php
/*
* Tłumaczenie widoczne po stronie klienta i także w administracji. Tłumaczenie jest konieczne
*/
// @claude-note: stałe napisy UI (przyciski, etykiety, komunikaty) — nie treści stron —
// zawsze przez $lang['...'], nigdy na sztywno w HTML/PHP. Zasada — patrz CLAUDE.md.

$lang['404_error'] = "Błąd 404 nie znaleziono strony";
$lang['and'] = "i";
$lang['and_or'] = "i/lub";
$lang['back'] = "powrót";
$lang['Data_not_found'] = "Nie znaleziono danych";
$lang['no'] = "nie";
$lang['Page_next'] = "Następna »";
$lang['Page_prev'] = "« Poprzednia";
$lang['Pages'] = "Strony";
$lang['Shop'] = "Sklep";
$lang['print'] = "drukuj";
$lang['Skip_to_content'] = "Przejdź do treści";
$lang['Skip_to_main_menu'] = "Przejdź do menu głównego";
$lang['yes'] = "tak";
$lang['call'] = "Zadzwoń";
$lang['phone'] = "Telefon";
$lang['location'] = "Lokalizacja";
$lang['navigate'] = "Nawiguj";
$lang['show_map'] = "Pokaż mapę";
$lang['write'] = "Napisz";
$lang['add_to_cart'] = "Dodaj do koszyka";
$lang['add_cart'] = "Koszyk";
$lang['choose_product_options'] = "Wybierz wszystkie opcje produktu przed dodaniem do koszyka.";
$lang['price_from'] = "od";
$lang['price_unit'] = "szt.";
$lang['more_from_brand'] = "Więcej modeli od";
$lang['or'] = "albo";
$lang['stock_available'] = "W magazynie";
$lang['stock_on_order'] = "Produkt dostępny na zamówienie";
$lang['stock_on_order_note'] = "Termin realizacji potwierdzimy po złożeniu zamówienia.";
$lang['see_all_products'] = "Zobacz wszystkie produkty";
$lang['see_all_blog'] = "Zobacz wszystkie aktualności";
$lang['instagram_subtitle'] = "Instagram";
$lang['instagram_title'] = "Śledź nas na Instagramie";
$lang['filters'] = "Filtry";
$lang['filter_button'] = "Filtruj";
$lang['clear'] = "Wyczyść";

/// kod rabatowy w zamówieniu
$lang['discount_code'] = "Kod rabatowy";
$lang['discount_placeholder'] = "Wpisz kod";
$lang['discount_apply'] = "Przelicz rabat";
$lang['discount_remove'] = "Usuń kod";
$lang['discount_label'] = "Rabat";
$lang['discount_applied'] = "Rabat %s%% naliczony.";
$lang['discount_invalid'] = "Kod rabatowy jest nieprawidłowy lub stracił ważność.";
$lang['discount_empty'] = "Wpisz kod rabatowy.";
$lang['discount_removed'] = "Kod rabatowy usunięty.";


/// panel użytkownika
$lang['login_title'] = "Masz konto? Zaloguj się";
$lang['login_button'] = "Zaloguj się";
$lang['register'] = "Rejestracja nowego konta";
$lang['edit_profile'] = "Edytuj profil";
/*
* Tłumaczenia widoczne tylko w administracji. Tłumaczenie nie jest wymagane
*/
$lang['Failed_login_wait_time'] = "Przekroczono limit prób logowania<br />Odczekaj 15 minut";
$lang['Add_files'] = "Dodaj pliki";
$lang['Address'] = "Przekieruj na adres";
$lang['Advanced_options'] = "Zaawansowane opcje:";
$lang['Back_end_only'] = "Administracja";
$lang['Cancel'] = "Anuluj";
$lang['Check_for_bug_fixes'] = "Sprawdź czy posiadasz wgrane <a href='http://opensolution.org/download/quick-cms-i-quick-cms-ext-poprawki.html' target='_blank'>wszystkie poprawki &raquo;</a>";
$lang['Choose_files_to_attach'] = "Wybierz pliki z serwera i zapisz formularz";
$lang['Content'] = "Treść";
$lang['Dashboard'] = "Pulpit";
$lang['Date'] = "Data";
$lang['Default'] = "Domyślne";
$lang['Delete'] = "Usuń";
$lang['Description'] = "Opis";
$lang['Display'] = "Wyświetl";
$lang['Display_all'] = "Wyświetl wszystkie";
$lang['Display_on_the_list'] = "Głowna miniatura";
$lang['Drop_files_to_upload'] = "Przeciągnij i upuść tutaj pliki z komputera aby załadować";
$lang['Edit'] = "Edytuj";
$lang['email'] = "E-mail";
$lang['Email'] = "Email";
$lang['Email_new'] = "Nowy email";
$lang['Email_old'] = "Aktualny email";
$lang['Failed_logs'] = "Ostatnie niepoprawne logowanie:";
$lang['File'] = "Plik";
$lang['Files'] = "Pliki";
$lang['Files_from_computer'] = "Pliki z komputera";
$lang['Files_on_server'] = "Pliki na serwerze";
$lang['Fill_required_fields'] = "Wypełnij poprawnie wymagane pola";
$lang['forgot_your_password'] = "nie pamiętasz hasła?";
$lang['Front_end_back_end'] = "Klient i administracja";
$lang['Full_description'] = "Opis pełny";
$lang['Help'] = "Pomoc";
$lang['Hide'] = "Ukryj";
$lang['Hide_in_sitemap'] = "Ukryj w mapie strony";
$lang['homepage'] = "strona główna";
$lang['Id'] = "Id";
$lang['Image'] = "Zdjęcie";
$lang['Image_over_max_dimension'] = "Zbyt duży obrazek aby stworzyć miniaturkę";
$lang['Incorrect_data'] = "Niepoprawne dane";
$lang['Increase_security'] = "Zwiększ bezpieczeństwo swojej strony.";
$lang['Inherit_from_parent'] = "Taki sam jak dla strony nadrzędnej";
$lang['Language'] = "Język";
$lang['Languages'] = "Języki";
$lang['License'] = "Licencja";
$lang['Location_page_details'] = "Umiejscowienie";
$lang['log_in'] = "zaloguj się";
$lang['Log_out'] = "Wyloguj się";
$lang['Loging'] = "Logowanie";
$lang['Manual'] = "Dokumentacja";
$lang['Mark_as_read'] = "Oznacz jako przeczytane";
$lang['Menu'] = "Menu";
$lang['Messages'] = "Informacje";
$lang['Meta_description'] = "Opis meta";
$lang['Meta_robots'] = "Instrukcja dla robotów";
$lang['more'] = "Więcej";
$lang['read_more'] = "Czytaj więcej";
$lang['More'] = "Więcej";
$lang['Name'] = "Tytuł";
$lang['Name_menu'] = "Nazwa w menu";
$lang['Need_more_ext'] = "Potrzebujesz więcej funkcji? Zobacz dodatki dla <a href='?p=plugins' target='_blank'>Quick.Cms.Ext &raquo;</a>";
$lang['New_language'] = "Nowy język";
$lang['New_page'] = "Nowa strona";
$lang['New_slider'] = "Nowy slider";
$lang['News'] = "Wiadomości z OpenSolution.org";
$lang['No_results_match'] = "Brak wyników odpowiadających";
$lang['none'] = "brak";
$lang['only_this_field_is_required'] = "- jedyne wymagane pole -";
$lang['Operation_completed'] = "Operacja wykonana poprawnie";
$lang['Operation_sure'] = "Czy chcesz wykonać tą operację?";
$lang['Operation_sure_delete'] = "Czy chcesz usunąć";
$lang['Options'] = "Opcje";
$lang['or_choose_from_server'] = "lub wybierz z serwera";
$lang['or_choose_slider'] = "lub wybierz";
$lang['Page_title'] = "Tytuł strony";
$lang['Pages_form'] = "Edycja strony";
$lang['Parent_page'] = "Przypisz do";
$lang['Password'] = "Hasło";
$lang['Password_new'] = "Nowe hasło";
$lang['Password_old'] = "Aktualne hasło";
$lang['Plugins'] = "Dodatki";
$lang['Position'] = "Kolejność";
$lang['Preview'] = "Podgląd";
$lang['required'] = "wymagane";
$lang['save'] = "Zapisz";
$lang['save_add_new'] = "Zapisz i dodaj kolejne";
$lang['save_list'] = "Zapisz i przejdź do listy";
$lang['Screenshots'] = "Zrzuty ekranu";
$lang['search'] = "Szukaj";
$lang['Select'] = "Wybierz";
$lang['Seo'] = "SEO";
$lang['Set'] = "Zestaw";
$lang['Settings'] = "Konfiguracja";
$lang['Settings_in_config_file'] = "Pozostałą konfigurację znajdziesz w pliku";
$lang['Short_description'] = "Opis krótki";
$lang['Slider'] = "Slider";
$lang['Sliders'] = "Slidery";
$lang['Sliders_form'] = "Edycja slidera";
$lang['Start_page'] = "Strona startowa";
$lang['Status'] = "Status";
$lang['Subpages_list_types'] = "Podstrony";
$lang['Support'] = "Wsparcie";
$lang['Template'] = "Szablon";
$lang['Thumbnail'] = "Miniaturka";
$lang['Tools'] = "Narzędzia";
$lang['Txt_to_short'] = "Zbyt mało tekstu";
$lang['Type_correct_email'] = "Podaj poprawny e-mail";
$lang['Type_login_password'] = "Wpisz email i hasło, które będą służyły do logowania";
$lang['Upload_failed'] = "Wgrywanie nieudane";
$lang['Upload_language_file'] = "Wgraj tłumaczenie";
$lang['Upload_language_file_info'] = "Pobierz tłumaczenie z <a href='http://opensolution.org/?p=download&sDir=Quick.Cms/translations' target='_blank'>OpenSolution</a>";
$lang['Url_name'] = "Nazwa url";
$lang['Use_language'] = "Stwórz język na podstawie";
$lang['Wrong_email_or_pass'] = "Nieprawidłowy email lub hasło";
$lang['Wrong_value'] = "Podaj poprawną wartość";

// Transmisja live — panel operatora
$lang['live_panel_login_required'] = "Panel meczowy wymaga zalogowania do panelu administracyjnego.";
$lang['live_panel_login_link'] = "Przejdź do logowania";
$lang['live_match_setup'] = "Konfiguracja meczu";
$lang['live_team_home'] = "Gospodarz";
$lang['live_team_away'] = "Gość";
$lang['live_save_teams'] = "Zapisz drużyny";
$lang['live_new_match'] = "Nowy mecz (wyzeruj)";
$lang['live_clock'] = "Zegar";
$lang['live_boards'] = "Plansze";
$lang['live_players'] = "Zawodnicy";
$lang['live_events'] = "Zdarzenia meczu";
$lang['live_half_1'] = "1 połowa";
$lang['live_half_2'] = "2 połowa";
$lang['live_pause'] = "Pauza";
$lang['live_resume'] = "Wznów";
$lang['live_reset'] = "Reset";
$lang['live_plus_min'] = "+1 min";
$lang['live_minus_min'] = "-1 min";
$lang['live_first_squad'] = "Wyjściowa 11";
$lang['live_reserve'] = "Rezerwa";
$lang['live_off_squad'] = "Poza kadrą";
$lang['live_minute'] = "Minuta";
$lang['live_cancel'] = "Anuluj";
$lang['live_save'] = "Zapisz";
$lang['live_delete'] = "Usuń";
$lang['live_clear_events'] = "Wyczyść historię zdarzeń";
$lang['live_confirm_new_match'] = "Wyzerować mecz? Wynik, zegar i historia zdarzeń zostaną skasowane.";
$lang['live_confirm_clear'] = "Skasować całą historię zdarzeń?";
$lang['live_confirm_delete'] = "Usunąć to zdarzenie?";
$lang['live_no_events'] = "Brak zdarzeń.";
$lang['live_no_teams'] = "Ustaw drużyny meczu w sekcji konfiguracji.";
$lang['live_half_short'] = "poł.";
$lang['live_broadcast_footer'] = "Transmisja live";
$lang['live_dot_title'] = "Status komunikatu na nakładce: żółty = w kolejce, zielony = wyświetlany";
$lang['live_scorebar_pos'] = "Pasek wyniku";
$lang['live_pos_left'] = "lewy róg";
$lang['live_pos_right'] = "prawy róg";
$lang['live_stat_goals'] = "Gole";
$lang['live_stat_yellow'] = "Żółte kartki";
$lang['live_stat_red'] = "Czerwone kartki";
$lang['live_stat_subs'] = "Zmiany";
$lang['live_replay'] = "Powtórka";
$lang['live_replay_button'] = "Powtórka na telebimie";
$lang['live_replay_sent'] = "Powtórka wysłana na telebim.";
?>